### ISSUE TITLE
attr.js:17 Error: <rect> attribute height: A negative value is not valid. ("-210")

### ISSUE THREAD

**Issue by mspruthv** [datencia/d3js-angular2-example#11]
Hi There,

You have done a wonderful job by creating this examples, really appreciate your effort here.

I'm facing a issue while creating brush for the area chart, i tried by my self but couldn't progress later i tried your approach but getting the same error.

Can you please help me out here to resolve this issue ?

Have attached the console logs for more details on the issue, source code too (renamed the extension from ts to txt).

[area-chart.component.txt](https://github.com/datencia/d3js-angular2-example/files/1176416/area-chart.component.txt)
![c1](https://user-images.githubusercontent.com/6239816/28618929-d804285e-7223-11e7-957a-3da39fa25ed7.png)
![c2](https://user-images.githubusercontent.com/6239816/28618930-d846565c-7223-11e7-82ce-71dfdee84b5b.png)

**Comment by mspruthv** [comment]
found the issue due to the negative height2, now this has been taken care.

**Comment by parthchat99** [comment]
How did you got the solution @mspruthv
