### ISSUE TITLE
Want to add two d3 charts in same page

### ISSUE THREAD

**Issue by alialrabi** [datencia/d3js-angular2-example#15]
I have implemented d3 pie chart and it works in svg element,but i need to change svg element to div and get it by id (i want to add two d3 charts in same page)

the code works fine when i use

    <svg width="360" height="260"></svg>

but when change to div element and get by id

     <div width="360" height="260" id="piechart"></div>
 it doesn't work

This is my angular code when using div

      private initSvg() {
          
       this.color = d3Scale.scaleOrdinal()
              .range(["#98abc5", "#8a89a6", "#7b6888", "#6b486b", "#a05d56", "#d0743c", "#ff8c00"]);
       this.arc = d3Shape.arc()
                      .outerRadius(this.radius - 10)
                      .innerRadius(0);
       this.labelArc = d3Shape.arc()
                           .outerRadius(this.radius - 40)
                           .innerRadius(this.radius - 40);
       this.pie = d3Shape.pie()
                      .sort(null)
                      .value((d: any) => d.population);
       this.svg = d3.select("#piechart")
                 .append("svg:svg");
                 .attr("transform", "translate(" + this.width / 2 + "," + this.height / 2 + ")");;
    }
    
     private drawPie() {
        let g = this.svg.selectAll(".arc")
                    .data(this.pie(this.pieData))
                    .enter().append("svg:svg")
                    .attr("class", "arc");
            g.append("path").attr("d", this.arc)
                    .style("fill", (d: any) => this.color(d.data.age) );
            g.append("text").attr("transform", (d: any) => "translate(" + this.labelArc.centroid(d) + ")")
                    .attr("dy", ".35em")
                    .text((d: any) => d.data.age);
     }

**Comment by datencia** [comment]
Hi @alialrabi do you get any error? 

In your example code, I see an extra semicolon after appending the `svg` element.

```javascript
this.svg = d3.select("#piechart")
             .append("svg:svg"); // <-------
             .attr("transform", "translate(" + this.width / 2 + "," + this.height / 2 + ")");
```

**Comment by JiunYiYang** [comment]
@datencia excuse me, I wanna ask that **why svg didn't show in my application** (build with Angular CLI)

Here I place your code into my `index.component.ts` file:

```typescript
import { Component, OnInit } from '@angular/core';

import * as d3 from 'd3-selection';
import * as d3Scale from "d3-scale";
import * as d3Shape from "d3-shape";
import * as d3Array from "d3-array";
import * as d3Axis from "d3-axis";

import { Stocks } from './../shared/data';

@Component({
  selector: 'app-index',
  templateUrl: './index.component.html',
  styleUrls: ['./index.component.css']
})
export class IndexComponent implements OnInit {

  title: string = 'D3.js with Angular 2!';
  subtitle: string = 'Line Chart';

  private margin = {top: 20, right: 20, bottom: 30, left: 50};
  private width: number;
  private height: number;
  private x: any;
  private y: any;
  private svg: any;
  private line: d3Shape.Line<[number, number]>;

  constructor() {
    this.width = 900 - this.margin.left - this.margin.right ;
    this.height = 500 - this.margin.top - this.margin.bottom;
  }

  ngOnInit() {
    this.initSvg()
    this.initAxis();
    this.drawAxis();
    this.drawLine();
  }

  private initSvg() {
    this.svg = d3.select("svg")
                 .append("svg:g")
                 .attr("transform", "translate(" + this.margin.left + "," + this.margin.top + ")");;
  }

  private initAxis() {
    this.x = d3Scale.scaleTime().range([0, this.width]);
    this.y = d3Scale.scaleLinear().range([this.height, 0]);
    this.x.domain(d3Array.extent(Stocks, (d) => d.date ));
    this.y.domain(d3Array.extent(Stocks, (d) => d.value ));
  }

  private drawAxis() {

    this.svg.append("svg:g")
          .attr("class", "axis axis--x")
          .attr("transform", "translate(0," + this.height + ")")
          .call(d3Axis.axisBottom(this.x));

    this.svg.append("svg:g")
          .attr("class", "axis axis--y")
          .call(d3Axis.axisLeft(this.y))
          .append("text")
          .attr("class", "axis-title")
          .attr("transform", "rotate(-90)")
          .attr("y", 6)
          .attr("dy", ".71em")
          .style("text-anchor", "end")
          .text("Price ($)");
  }

  private drawLine() {
    this.line = d3Shape.line()
                       .x( (d: any) => this.x(d.date) )
                       .y( (d: any) => this.y(d.value) );

    this.svg.append("svg:path")
            .datum(Stocks)
            .attr("class", "line")
            .attr("d", this.line);
  }

}
```
And I put the template in `index.component.html`:
```html
<h1>{{title}}</h1>
<h2>{{subtitle}}</h2>
<svg width="900" height="500"></svg>
```

But in browser I get this only, with no charts inside `<svg></svg>` :
```html
<svg _ngcontent-c5="" height="500" width="900"></svg>
```
The `data.ts` file is as your original one.
And here's my file branch look like:

```
node_modules－
src－
　　| app－
　　　　　| index－
　　　　　　　　　| index.component.html
　　　　　　　　　| index.component.scss
　　　　　　　　　| index.component.spec.ts
　　　　　　　　　| index.component.ts
　　　　　| shared－
　　　　　　　　　| data.ts
　　　　　| app.component.html
　　　　　| app.component.scss
　　　　　| app.component.spec.ts
　　　　　| app.component.ts
　　　　　| app.module.ts
　　| assets－
　　| environment－
　　| index.html
　　| main.ts
　　| style.scss
.angular-cli.json
.gitignore
package.json
...
```

Please lend me a helping hand for this strange problem...
Thanks a lot!

**Comment by datencia** [comment]
Hi @JiunYiYang Please open a new issue and don't reuse an existing one.

**Comment by datencia** [comment]
Closed due to inactivity.
